package com.tuobuxie.entity;
// Generated 2016-11-24 15:23:31 by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.alibaba.fastjson.JSON;

/**
 * TGoodsDetail generated by hbm2java
 */
@Entity
@Table(name = "T_GOODS_DETAIL", schema = "TUOBUXIE")
public class TGoodsDetail implements java.io.Serializable {

	private Integer CId;
	private String CDescribe;
	private String CFlavor;

	public TGoodsDetail() {
	}

	public TGoodsDetail(Integer CId) {
		this.CId = CId;
	}

	public TGoodsDetail(Integer CId, String CDescribe, String CFlavor) {
		this.CId = CId;
		this.CDescribe = CDescribe;
		this.CFlavor = CFlavor;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="S_TGoodsDetail")
	@SequenceGenerator(name="S_TGoodsDetail", allocationSize=1, initialValue=1,sequenceName="S_TGoodsDetail")
	@Column(name = "C_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	@Column(name = "C_DESCRIBE", length = 1024)
	public String getCDescribe() {
		return this.CDescribe;
	}

	public void setCDescribe(String CDescribe) {
		this.CDescribe = CDescribe;
	}

	@Column(name = "C_FLAVOR", length = 2)
	public String getCFlavor() {
		return this.CFlavor;
	}

	public void setCFlavor(String CFlavor) {
		this.CFlavor = CFlavor;
	}
	@Override
	public String toString() {
		return JSON.toJSONString(this);
	}
}
